### ISSUE TITLE
versionGroup.dependencyTypes takes "peerDependencies" instead of documented "peer"

### ISSUE THREAD

**Issue by dsilvasc** [JamieMason/syncpack#96]
## Description

The readme says `versionGroup.dependencyTypes` accepts "peer" as a value.  In this example, I have a violation this should catch but doesn't:

```yaml
filter: webpack
versionGroups:
  - packages: ["**"]
    dependencies: ["webpack"]
    dependencyTypes: ["peer"]
    pinVersion: "5.73.0"
```

```
$ node node_modules/.bin/syncpack list-mismatches
```

Syncpack catches the mismatch if I use "peerDependencies" instead:

```yaml
filter: webpack
versionGroups:
  - packages: ["**"]
    dependencies: ["webpack"]
    dependencyTypes: ["peerDependencies"]
    pinVersion: "5.73.0"
```

```
$ node node_modules/.bin/syncpack list-mismatches
= Version Group 1 ===============================================================
- webpack: 5.73.0 is the highest valid semver version in use
  5.74.0 in peerDependencies of common/tools/package.json
```

## Suggested Solution

Either update the readme to say it should be peerDependencies, or update the versionGroup handler to handle "peer", or support both?
